name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew :app:test
  ui_tests:
    name: Run UI tests
    runs-on: macos-latest
    steps:
      - name: Checkout codePeopleLocalDataSourceTest.kt:31
        uses: actions/checkout@v2
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
          with:
          api-level: 31
          script: ./gradlew connectedCheck
